seed: 27

baseline:
  dataset_path: ./Data/Imagenette
  dataset_name: Imagenette
  non_iid_per: 0.1
  num_clients: 12
  fraction_clients: 0.5
  num_rounds: 30
  num_epochs: 5
  batch_size: 32
  local_lr: 0.01
  global_lr: 1.0
  num_classes: 10
  criterion: torch.nn.CrossEntropyLoss

surrogate:
  dataset_path: ./Data/Imagenette
  dataset_name: Imagenette
  non_iid_per: 0.1
  num_clients: 12
  fraction_clients: 0.5
  num_rounds: 5
  num_epochs: 5
  batch_size: 32
  local_lr: 0.0005
  global_lr: 1.0
  num_classes: 10
  criterion: torch.nn.CrossEntropyLoss
  pretrained: true
  client_id: 0

attack:
  type: pgd
  poison_rate: 0.25
  target_label: 0
  epsilon: 0.03137255
  step_size: 0.00784314
  iters: 10
  criterion: torch.nn.CrossEntropyLoss

attack_run:
  malicious_fraction: 0.2
  seed: 2024
